# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_server.proto\"B\n\x13\x43reateShapeResponse\x12\x1a\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x05.Code\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\x10GetShapeResponse\x12\x1a\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x05.Code\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\x05shape\x18\x03 \x01(\x0b\x32\x06.Shape\"\x1f\n\tShapeType\x12\x12\n\nshape_type\x18\x01 \x01(\t\"\x1b\n\x07ShapeId\x12\x10\n\x08shape_id\x18\x01 \x01(\t\"J\n\x05Shape\x12\x10\n\x08shape_id\x18\x01 \x01(\t\x12\x12\n\nshape_type\x18\x02 \x01(\t\x12\x1b\n\x06\x63oords\x18\x03 \x03(\x0b\x32\x0b.ShapeCoord\"8\n\nShapeCoord\x12\x0e\n\x01x\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y*6\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_SHAPE\x10\x64\x12\x13\n\x0fSHAPE_NOT_FOUND\x10\x65\x32j\n\nGrpcServer\x12\x31\n\x0b\x43reateShape\x12\n.ShapeType\x1a\x14.CreateShapeResponse\"\x00\x12)\n\x08GetShape\x12\x08.ShapeId\x1a\x11.GetShapeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODE']._serialized_start=373
  _globals['_CODE']._serialized_end=427
  _globals['_CREATESHAPERESPONSE']._serialized_start=21
  _globals['_CREATESHAPERESPONSE']._serialized_end=87
  _globals['_GETSHAPERESPONSE']._serialized_start=89
  _globals['_GETSHAPERESPONSE']._serialized_end=175
  _globals['_SHAPETYPE']._serialized_start=177
  _globals['_SHAPETYPE']._serialized_end=208
  _globals['_SHAPEID']._serialized_start=210
  _globals['_SHAPEID']._serialized_end=237
  _globals['_SHAPE']._serialized_start=239
  _globals['_SHAPE']._serialized_end=313
  _globals['_SHAPECOORD']._serialized_start=315
  _globals['_SHAPECOORD']._serialized_end=371
  _globals['_GRPCSERVER']._serialized_start=429
  _globals['_GRPCSERVER']._serialized_end=535
# @@protoc_insertion_point(module_scope)
